"use client";
import { useEffect, useRef } from "react";
import Link from "next/link";
import { trackEvent } from "../lib/analytics";
import { EXPEDIA_GENERAL_AFFILIATE_URL } from "../lib/revenuePartners";
const rel = "nofollow sponsored noopener noreferrer";
function useView(name, type) { useEffect(() => trackEvent(name, { component_type: type, placement: "conversion_section", page: location.pathname, page_path: location.pathname }), [name, type]); }
export function ConversionScrollAnalytics() { const fired = useRef(new Set()); useEffect(() => { const run = () => { const max = document.documentElement.scrollHeight - innerHeight; const pct = max > 0 ? scrollY / max * 100 : 100; [50, 90].forEach((d) => { if (pct >= d && !fired.current.has(d)) { fired.current.add(d); trackEvent(`scroll_${d}`, { scroll_depth: d, page_path: location.pathname }); } }); }; addEventListener("scroll", run, { passive: true }); run(); return () => removeEventListener("scroll", run); }, []); return null; }
export function QuickDealCard() { useView("deal_card_view", "quick_deal"); return <article className="content-card"><p className="best-for-tag">Popular Florida planning paths</p><h2>Turn Inspiration Into A Trip Plan</h2><ul><li>✓ Compare destinations</li><li>✓ Review family and beach options</li><li>✓ Connect hotels, flights, and activities</li></ul><Link className="affiliate-cta" href="/vacation-packages" onClick={() => trackEvent("deal_card_click", { component_type: "QuickDealCard", placement: "conversion_section", page: location.pathname, page_path: location.pathname })}>Explore Planning Options</Link></article>; }
export function RecommendedPartnerCard() { useView("partner_card_view", "recommended_partner"); const click = () => { const p = { component_type: "RecommendedPartnerCard", placement: "conversion_section", page: location.pathname, partner: "expedia", page_path: location.pathname, outbound_url: EXPEDIA_GENERAL_AFFILIATE_URL }; trackEvent("partner_card_click", p); trackEvent("affiliate_click", p); }; return <article className="content-card"><p className="best-for-tag">Recommended booking partner</p><h2>Expedia</h2><p>Compare travel options when you are ready to move from Florida inspiration into a bookable trip.</p><a className="affiliate-cta" href={EXPEDIA_GENERAL_AFFILIATE_URL} target="_blank" rel={rel} onClick={click}>View Current Deals</a><p className="affiliate-disclosure">Affiliate link. We may earn a commission at no extra cost to you.</p></article>; }
