/* eslint-disable @next/next/no-html-link-for-pages */
"use client";
import { useState, useSyncExternalStore } from "react";
const KEY="fdn-my-trip-v31";
const valid=r=>r.startsWith("/")&&!r.startsWith("//")&&!r.includes("..")&&!r.includes("\\");
const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v.filter(x=>valid(x.route)):[]}catch{return[]}};
const track=(name,p)=>{if(window.gtag)window.gtag("event",name,p);else{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...p})}};
export default function TripRetentionTools({route,title,image="",pageType="trip_reality_guide",articleCluster="v30_trip_reality"}){const site="floridadealshub",id=site+":"+route,[savedState,setSaved]=useState(null),storedSaved=useSyncExternalStore(()=>()=>{},()=>read().some(x=>x.id===id),()=>false),saved=savedState??storedSaved,[rating,setRating]=useState(""),[comment,setComment]=useState(""),[sent,setSent]=useState(false);
 function toggle(){let items=read();if(saved){items=items.filter(x=>x.id!==id);track("remove_trip_item",{site,route,item_type:pageType})}else{items.push({id,type:pageType,site,route,title,destination:"",image,savedAt:new Date().toISOString(),lastVisitedAt:new Date().toISOString(),liveDataKey:"",notes:""});track("save_trip_item",{site,route,item_type:pageType})}localStorage.setItem(KEY,JSON.stringify(items));setSaved(!saved)}
 async function submit(e){e.preventDefault();const r=await fetch("/api/visitor-feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,route,pageType,articleCluster,rating,comment,website:""})});if(r.ok){track("visitor_feedback",{site,route,page_type:pageType,article_cluster:articleCluster,rating,has_comment:Boolean(comment.trim())});setSent(true)}}
 return <section className="v31-tools"><div><p className="eyebrow">Return to this plan</p><h2>Save this guide</h2><p>Saved only in this browser on this site. No account or cross-site tracking.</p><button onClick={toggle}>{saved?"Saved - Remove":"Save to My Trip"}</button> <a href="/my-trip" onClick={()=>track("view_my_trip",{site,route:"/my-trip"})}>View My Trip</a></div><div>{sent?<><h2>Thanks for the feedback</h2><p>Your response helps us improve this guide.</p></>:<form onSubmit={submit}><fieldset><legend>Was this page useful?</legend>{["yes","mostly","no"].map(x=><label key={x}><input name="rating" onChange={()=>setRating(x)} type="radio"/> {x==="yes"?"Yes":x==="mostly"?"Mostly":"No"}</label>)}</fieldset>{rating?<label>What were you still trying to figure out? (optional)<textarea maxLength={280} onChange={e=>setComment(e.target.value)} value={comment}/></label>:null}<input className="v31-hp" name="website" tabIndex={-1}/><button disabled={!rating}>Send feedback</button></form>}</div><style jsx>{`.v31-tools{max-width:1180px;margin:0 auto 48px;padding:0 20px;display:grid;grid-template-columns:1fr 1fr;gap:20px}.v31-tools>div{border:1px solid #d9e2ec;border-radius:8px;padding:24px;background:#fff}.v31-tools h2{margin:6px 0}.v31-tools button{background:#087f8c;color:#fff;border:0;border-radius:6px;padding:12px 16px;font-weight:700}.v31-tools a{margin-left:12px;font-weight:700;color:#087f8c}.v31-tools fieldset{border:0;padding:0}.v31-tools legend{font-size:20px;font-weight:800;margin-bottom:10px}.v31-tools label{display:block;margin:8px 0;font-weight:700}.v31-tools textarea{display:block;width:100%;min-height:80px;margin-top:8px;padding:10px}.v31-hp{display:none}@media(max-width:720px){.v31-tools{grid-template-columns:1fr;padding:0 16px}}`}</style></section>}
